### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by lnbailey**
Created grid and styling for products

### CODE REVIEW

**Comment by copypastedeveloper** [comment]
## Requirements
- [ ]  In the [additional styling details](https://github.com/nss-evening-cohort-04/mastery-exercise-html-lnbailey#additional-style-requirements) section, #5 specifies the **details** be bolded, not the headers.

## Improvements
- [ ] Try and center the cards on the page.

Looks very nice.  Great job!

**Comment by lnbailey** [comment]
@ncgonz Fixed it

**Comment by copypastedeveloper** [comment]
@lnbailey this is looking good.  Digging the change to `<ul>`+`<li>` but for the love of God close your `<br/>` tags!!!!!!!!!!!!! AHHHHHHH!!!!!!!!!!!

**Comment by lnbailey** [comment]
@ncgonz Sorry! I did them as <br /> for years. Someone told me it wasn't needed. Trying to keep up with the ever-changing rules. Fixed.

**Comment by copypastedeveloper** [comment]
@lnbailey definitely not a rule (just a great idea that makes me happy).  When i'm grokking things it makes it easier to see an open and a close tag, or a self-closing tag.  Otherwise my eyes just keep looking for the closing tag.

**Comment by copypastedeveloper** [comment]
👍

**Comment by lnbailey** [comment]
@ncgonz  Good to know. Do I do my own merge?

**Comment by copypastedeveloper** [comment]
@lnbailey yup.

**Pull request merged**
